#!/bin/bash

CRIB_SED="scripts/cribs.sed"

if [ -e scripts/cribs.sed ]; then
	old_hash="$(cat "${CRIB_SED}" | sha1sum)"
fi

echo 'CRIB_SHEETS=\' > cribs.d
rm -rf "${CRIB_SED}.new"
for i in cribs/*.txt; do
	tag="%CRIB_$(basename "$(echo "${i}" | sed -e 's/.txt//g')")%"
	crib_name="$(echo "${i}" | sed -e 's/.txt/.crib/g')"
	echo "${crib_name} \\" >> cribs.d
	echo "/${tag}/r ${crib_name}" >> "${CRIB_SED}.new"
	echo "s/${tag}//g" >> "${CRIB_SED}.new"
done
echo >> cribs.d

for i in cribs/*.txt; do
	scripts/crib_deps.py "${i}" >> cribs.d
done

if [ -z "${old_hash}" ]; then
	mv "${CRIB_SED}.new" "${CRIB_SED}"
else
	new_hash="$(cat scripts/cribs.sed.new | sha1sum)"
	if [ "${new_hash}" != "${old_hash}" ]; then
		mv "${CRIB_SED}.new" "${CRIB_SED}"
	else
		rm -rf "${CRIB_SED}.new"
	fi
fi

exit 0
