#!/bin/bash

if [ "$1" = "-d" ]; then
	# Generate make dependencies.
	cat data/people.csv | while IFS=, read tag name role phone email imgurl crap; do
		if [ "${tag:0:1}" = "#" ]; then
			continue
		fi
		echo "CLEAN+=${tag}.html"
		echo "${tag}.html: data/people.csv"
		echo -e "\tscripts/contacts"
		echo
	done
	exit 0
fi

# Otherwise, generate html
cat data/people.csv | while IFS=, read tag name role phone email imgurl crap; do
	if [ "${tag:0:1}" = "#" ]; then
		continue
	fi
	fname="${tag}.html"
	if [ -z "${imgurl}" ]; then
		imgurl="images/nopic.png"
	fi
	cat > "${fname}" << ENDL
<a href="mailto:${email}"><img class="ps_icon" src="${imgurl}" height="128" width="128" alt="${name}"/></a>
<div class="ps_header">${name}, ${role}</div>
<div>${phone}</div>
<div class="email">${email}</div>
ENDL
done
exit 0
