#!/bin/bash

MODE="$1"
if [ "${MODE}" != "dep" -a "${MODE}" != "sed" ]; then
	echo "Modes are \"dep\" or \"sed\". \"${MODE}\" not recognized."
	exit 1
fi

case "${MODE}" in
"dep")
	OUTPUT="cribs.d"
	;;
"sed")
	OUTPUT="scripts/cribs.sed"
	;;
esac

if [ -e "${OUTPUT}" ]; then
	old_hash="$(sha1sum "${OUTPUT}" 2> /dev/null)"
fi

case "${MODE}" in
"dep")
	echo 'CRIB_SHEETS=\' > "${OUTPUT}.new"
	for i in cribs/*.txt; do
		crib_name="$(echo "${i}" | sed -e 's/.txt/.crib/g')"
		echo "${crib_name} \\" >> "${OUTPUT}.new"
	done
	echo >> "${OUTPUT}.new"

	for i in cribs/*.txt; do
		scripts/crib_deps.py "${i}" >> "${OUTPUT}.new"
		echo >> "${OUTPUT}.new"
	done
	;;
"sed")
	for i in cribs/*.txt; do
		tag="%CRIB_$(basename "$(echo "${i}" | sed -e 's/.txt//g')")%"
		crib_name="$(echo "${i}" | sed -e 's/.txt/.crib/g')"
		echo "/${tag}/r ${crib_name}" >> "${OUTPUT}.new"
		echo "s/${tag}//g" >> "${OUTPUT}.new"
	done
	;;
esac

if [ -z "${old_hash}" ]; then
	mv "${OUTPUT}.new" "${OUTPUT}"
else
	new_hash="$(sha1sum "${OUTPUT}.new")"
	if [ "${new_hash}" != "${old_hash}" ]; then
		mv "${OUTPUT}.new" "${OUTPUT}"
	else
		rm -rf "${OUTPUT}.new"
	fi
fi

exit 0
