#!/bin/bash -e

echo '[' > data/eventdb.js
cat data/dance_events.js data/big_events.js data/class_events.js data/travel_events.js data/hidden_events.js data/news_events.js >> data/eventdb.js
cat >> data/eventdb.js << ENDL
{}
]
ENDL

exit 0
